dist: bionic

language: python

python:
 - "3.7"

addons:
  postgresql: "10"
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - postgresql-10-postgis-2.4
      - rabbitmq-server

install:
 # TimescaleDB
 - sudo add-apt-repository -y ppa:timescale/timescaledb-ppa
 - sudo apt-get update
 - sudo apt-get install -y timescaledb-postgresql-10
 - sudo bash -c "echo \"shared_preload_libraries = 'timescaledb'\" >>/etc/postgresql/10/main/postgresql.conf"
 - sudo service postgresql restart

 - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<2.2.3'
 - pip install codecov black flake8 isort
 - pip install psycopg2==2.7.4
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - git clone https://github.com/openmeteo/enhydris.git ../enhydris
 - pip install -r ../enhydris/requirements.txt
 - pip install -r ../enhydris/requirements-dev.txt

before_script:
 - psql -U postgres -c "create extension postgis"
 - psql -U postgres -c "create database openmeteo"
 - cp .travis-settings.py ../enhydris/enhydris_project/settings/local.py
 - cd ../enhydris
 - ln -s ../enhydris-autoprocess/enhydris_autoprocess .

script:
 - black --check enhydris_autoprocess
 - flake8 --max-line-length=88 enhydris_autoprocess
 - isort --recursive --check-only --diff enhydris_autoprocess
 - ./manage.py makemigrations --check
 - coverage run --include="./enhydris_autoprocess/*" --omit="*/tests/*","*/tests.py" ./manage.py test -v2 enhydris_autoprocess

after_success:
 - codecov
