# Generated by Django 2.1.8 on 2019-05-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("enhydris", "0011_gentity_event_user_optional")]

    operations = [
        migrations.CreateModel(
            name="RangeCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upper_bound", models.FloatField()),
                ("lower_bound", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_timeseries",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="enhydris.Timeseries",
                    ),
                ),
                (
                    "target_timeseries",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_timeseries_of",
                        to="enhydris.Timeseries",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rangecheck",
            name="validation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris_autoprocess.Validation",
            ),
        ),
    ]
