# Generated by Django 2.1.8 on 2019-05-28 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0011_gentity_event_user_optional"),
        ("enhydris_autoprocess", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="validation",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enhydris.Station"
            ),
            preserve_default=False,
        )
    ]
