# Generated by Django 2.2.4 on 2019-08-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("enhydris_autoprocess", "0003_rename_validation_to_auto_process")]

    operations = [
        migrations.RemoveField(model_name="RangeCheck", name="id"),
        migrations.RenameField(
            model_name="RangeCheck", old_name="auto_process", new_name="autoprocess_ptr"
        ),
        migrations.AlterField(
            model_name="RangeCheck",
            name="autoprocess_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="enhydris_autoprocess.AutoProcess",
            ),
        ),
        migrations.CreateModel(
            name="CurveInterpolation",
            fields=[
                (
                    "autoprocess_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="enhydris_autoprocess.AutoProcess",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CurvePoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                (
                    "curve_interpolation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enhydris_autoprocess.CurveInterpolation",
                    ),
                ),
            ],
        ),
    ]
