# Generated by Django 2.2.7 on 2019-11-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("enhydris_autoprocess", "0005_curveperiod")]

    operations = [
        migrations.AddField(
            model_name="rangecheck",
            name="soft_lower_bound",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rangecheck",
            name="soft_upper_bound",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
