# Generated by Django 2.2.7 on 2020-01-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris_autoprocess", "0007_aggregation"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregation",
            name="max_missing",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text=(
                    "Defines what happens if some of the source records corresponding "
                    "to a destination record are missing. Suppose you are aggregating "
                    "ten-minute to hourly and for 23 January between 12:00 and 13:00 "
                    "there are only four nonempty records in the ten-minute time "
                    "series (instead of the usual six). If you set this to 1 or lower, "
                    "the hourly record for 23 January 13:00 will be empty; if 2 or "
                    "larger, the hourly value will be derived from the four values. In "
                    "the latter case, the MISS flag will also be set in the resulting "
                    "record."
                ),
            ),
        ),
    ]
